package com.linkit.company.core.designsystem.foundation.typography

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import com.linkit.company.core.designsystem.foundation.typography.token.TypographyTokens

internal val LocalTypography = staticCompositionLocalOf { LinkItTypography() }

@Immutable
class LinkItTypography internal constructor(
    val display1Regular: TextStyle,
    val display1Medium: TextStyle,
    val display1Semibold: TextStyle,
    val display1Bold: TextStyle,
    val display2Regular: TextStyle,
    val display2Medium: TextStyle,
    val display2Semibold: TextStyle,
    val display2Bold: TextStyle,
    val title1Regular: TextStyle,
    val title1Medium: TextStyle,
    val title1Semibold: TextStyle,
    val title1Bold: TextStyle,
    val title2Regular: TextStyle,
    val title2Medium: TextStyle,
    val title2Semibold: TextStyle,
    val title2Bold: TextStyle,
    val title3Regular: TextStyle,
    val title3Medium: TextStyle,
    val title3Semibold: TextStyle,
    val title3Bold: TextStyle,
    val heading1Regular: TextStyle,
    val heading1Medium: TextStyle,
    val heading1Semibold: TextStyle,
    val heading1Bold: TextStyle,
    val heading2Regular: TextStyle,
    val heading2Medium: TextStyle,
    val heading2Semibold: TextStyle,
    val heading2Bold: TextStyle,
    val headline1Regular: TextStyle,
    val headline1Medium: TextStyle,
    val headline1Semibold: TextStyle,
    val headline1Bold: TextStyle,
    val headline2Regular: TextStyle,
    val headline2Medium: TextStyle,
    val headline2Semibold: TextStyle,
    val headline2Bold: TextStyle,
    val body1NormalRegular: TextStyle,
    val body1NormalMedium: TextStyle,
    val body1NormalSemibold: TextStyle,
    val body1NormalBold: TextStyle,
    val body1ReadingRegular: TextStyle,
    val body1ReadingMedium: TextStyle,
    val body1ReadingSemibold: TextStyle,
    val body1ReadingBold: TextStyle,
    val body2NormalRegular: TextStyle,
    val body2NormalMedium: TextStyle,
    val body2NormalSemibold: TextStyle,
    val body2NormalBold: TextStyle,
    val body2ReadingRegular: TextStyle,
    val body2ReadingMedium: TextStyle,
    val body2ReadingSemibold: TextStyle,
    val body2ReadingBold: TextStyle,
    val label1NormalRegular: TextStyle,
    val label1NormalMedium: TextStyle,
    val label1NormalSemibold: TextStyle,
    val label1NormalBold: TextStyle,
    val label1ReadingRegular: TextStyle,
    val label1ReadingMedium: TextStyle,
    val label1ReadingSemibold: TextStyle,
    val label1ReadingBold: TextStyle,
    val label2Regular: TextStyle,
    val label2Medium: TextStyle,
    val label2Semibold: TextStyle,
    val label2Bold: TextStyle,
    val caption1Regular: TextStyle,
    val caption1Medium: TextStyle,
    val caption1Semibold: TextStyle,
    val caption1Bold: TextStyle,
    val caption2Regular: TextStyle,
    val caption2Medium: TextStyle,
    val caption2Semibold: TextStyle,
    val caption2Bold: TextStyle,
    val caption3Regular: TextStyle,
    val caption3Medium: TextStyle,
    val caption3Semibold: TextStyle,
    val caption3Bold: TextStyle,
) {
    constructor(
        defaultColor: Color = Color.Black,
        display1Regular: TextStyle = TypographyTokens.Display1Regular.copy(color = defaultColor),
        display1Medium: TextStyle = TypographyTokens.Display1Medium.copy(color = defaultColor),
        display1Semibold: TextStyle = TypographyTokens.Display1Semibold.copy(color = defaultColor),
        display1Bold: TextStyle = TypographyTokens.Display1Bold.copy(color = defaultColor),
        display2Regular: TextStyle = TypographyTokens.Display2Regular.copy(color = defaultColor),
        display2Medium: TextStyle = TypographyTokens.Display2Medium.copy(color = defaultColor),
        display2Semibold: TextStyle = TypographyTokens.Display2Semibold.copy(color = defaultColor),
        display2Bold: TextStyle = TypographyTokens.Display2Bold.copy(color = defaultColor),
        title1Regular: TextStyle = TypographyTokens.Title1Regular.copy(color = defaultColor),
        title1Medium: TextStyle = TypographyTokens.Title1Medium.copy(color = defaultColor),
        title1Semibold: TextStyle = TypographyTokens.Title1Semibold.copy(color = defaultColor),
        title1Bold: TextStyle = TypographyTokens.Title1Bold.copy(color = defaultColor),
        title2Regular: TextStyle = TypographyTokens.Title2Regular.copy(color = defaultColor),
        title2Medium: TextStyle = TypographyTokens.Title2Medium.copy(color = defaultColor),
        title2Semibold: TextStyle = TypographyTokens.Title2Semibold.copy(color = defaultColor),
        title2Bold: TextStyle = TypographyTokens.Title2Bold.copy(color = defaultColor),
        title3Regular: TextStyle = TypographyTokens.Title3Regular.copy(color = defaultColor),
        title3Medium: TextStyle = TypographyTokens.Title3Medium.copy(color = defaultColor),
        title3Semibold: TextStyle = TypographyTokens.Title3Semibold.copy(color = defaultColor),
        title3Bold: TextStyle = TypographyTokens.Title3Bold.copy(color = defaultColor),
        heading1Regular: TextStyle = TypographyTokens.Heading1Regular.copy(color = defaultColor),
        heading1Medium: TextStyle = TypographyTokens.Heading1Medium.copy(color = defaultColor),
        heading1Semibold: TextStyle = TypographyTokens.Heading1Semibold.copy(color = defaultColor),
        heading1Bold: TextStyle = TypographyTokens.Heading1Bold.copy(color = defaultColor),
        heading2Regular: TextStyle = TypographyTokens.Heading2Regular.copy(color = defaultColor),
        heading2Medium: TextStyle = TypographyTokens.Heading2Medium.copy(color = defaultColor),
        heading2Semibold: TextStyle = TypographyTokens.Heading2Semibold.copy(color = defaultColor),
        heading2Bold: TextStyle = TypographyTokens.Heading2Bold.copy(color = defaultColor),
        headline1Regular: TextStyle = TypographyTokens.Headline1Regular.copy(color = defaultColor),
        headline1Medium: TextStyle = TypographyTokens.Headline1Medium.copy(color = defaultColor),
        headline1Semibold: TextStyle = TypographyTokens.Headline1Semibold.copy(color = defaultColor),
        headline1Bold: TextStyle = TypographyTokens.Headline1Bold.copy(color = defaultColor),
        headline2Regular: TextStyle = TypographyTokens.Headline2Regular.copy(color = defaultColor),
        headline2Medium: TextStyle = TypographyTokens.Headline2Medium.copy(color = defaultColor),
        headline2Semibold: TextStyle = TypographyTokens.Headline2Semibold.copy(color = defaultColor),
        headline2Bold: TextStyle = TypographyTokens.Headline2Bold.copy(color = defaultColor),
        body1NormalRegular: TextStyle = TypographyTokens.Body1NormalRegular.copy(color = defaultColor),
        body1NormalMedium: TextStyle = TypographyTokens.Body1NormalMedium.copy(color = defaultColor),
        body1NormalSemibold: TextStyle = TypographyTokens.Body1NormalSemibold.copy(color = defaultColor),
        body1NormalBold: TextStyle = TypographyTokens.Body1NormalBold.copy(color = defaultColor),
        body1ReadingRegular: TextStyle = TypographyTokens.Body1ReadingRegular.copy(color = defaultColor),
        body1ReadingMedium: TextStyle = TypographyTokens.Body1ReadingMedium.copy(color = defaultColor),
        body1ReadingSemibold: TextStyle = TypographyTokens.Body1ReadingSemibold.copy(color = defaultColor),
        body1ReadingBold: TextStyle = TypographyTokens.Body1ReadingBold.copy(color = defaultColor),
        body2NormalRegular: TextStyle = TypographyTokens.Body2NormalRegular.copy(color = defaultColor),
        body2NormalMedium: TextStyle = TypographyTokens.Body2NormalMedium.copy(color = defaultColor),
        body2NormalSemibold: TextStyle = TypographyTokens.Body2NormalSemibold.copy(color = defaultColor),
        body2NormalBold: TextStyle = TypographyTokens.Body2NormalBold.copy(color = defaultColor),
        body2ReadingRegular: TextStyle = TypographyTokens.Body2ReadingRegular.copy(color = defaultColor),
        body2ReadingMedium: TextStyle = TypographyTokens.Body2ReadingMedium.copy(color = defaultColor),
        body2ReadingSemibold: TextStyle = TypographyTokens.Body2ReadingSemibold.copy(color = defaultColor),
        body2ReadingBold: TextStyle = TypographyTokens.Body2ReadingBold.copy(color = defaultColor),
        label1NormalRegular: TextStyle = TypographyTokens.Label1NormalRegular.copy(color = defaultColor),
        label1NormalMedium: TextStyle = TypographyTokens.Label1NormalMedium.copy(color = defaultColor),
        label1NormalSemibold: TextStyle = TypographyTokens.Label1NormalSemibold.copy(color = defaultColor),
        label1NormalBold: TextStyle = TypographyTokens.Label1NormalBold.copy(color = defaultColor),
        label1ReadingRegular: TextStyle = TypographyTokens.Label1ReadingRegular.copy(color = defaultColor),
        label1ReadingMedium: TextStyle = TypographyTokens.Label1ReadingMedium.copy(color = defaultColor),
        label1ReadingSemibold: TextStyle = TypographyTokens.Label1ReadingSemibold.copy(color = defaultColor),
        label1ReadingBold: TextStyle = TypographyTokens.Label1ReadingBold.copy(color = defaultColor),
        label2Regular: TextStyle = TypographyTokens.Label2Regular.copy(color = defaultColor),
        label2Medium: TextStyle = TypographyTokens.Label2Medium.copy(color = defaultColor),
        label2Semibold: TextStyle = TypographyTokens.Label2Semibold.copy(color = defaultColor),
        label2Bold: TextStyle = TypographyTokens.Label2Bold.copy(color = defaultColor),
        caption1Regular: TextStyle = TypographyTokens.Caption1Regular.copy(color = defaultColor),
        caption1Medium: TextStyle = TypographyTokens.Caption1Medium.copy(color = defaultColor),
        caption1Semibold: TextStyle = TypographyTokens.Caption1Semibold.copy(color = defaultColor),
        caption1Bold: TextStyle = TypographyTokens.Caption1Bold.copy(color = defaultColor),
        caption2Regular: TextStyle = TypographyTokens.Caption2Regular.copy(color = defaultColor),
        caption2Medium: TextStyle = TypographyTokens.Caption2Medium.copy(color = defaultColor),
        caption2Semibold: TextStyle = TypographyTokens.Caption2Semibold.copy(color = defaultColor),
        caption2Bold: TextStyle = TypographyTokens.Caption2Bold.copy(color = defaultColor),
        caption3Regular: TextStyle = TypographyTokens.Caption3Regular.copy(color = defaultColor),
        caption3Medium: TextStyle = TypographyTokens.Caption3Medium.copy(color = defaultColor),
        caption3Semibold: TextStyle = TypographyTokens.Caption3Semibold.copy(color = defaultColor),
        caption3Bold: TextStyle = TypographyTokens.Caption3Bold.copy(color = defaultColor),
    ) : this(
        display1Regular = display1Regular,
        display1Medium = display1Medium,
        display1Semibold = display1Semibold,
        display1Bold = display1Bold,
        display2Regular = display2Regular,
        display2Medium = display2Medium,
        display2Semibold = display2Semibold,
        display2Bold = display2Bold,
        title1Regular = title1Regular,
        title1Medium = title1Medium,
        title1Semibold = title1Semibold,
        title1Bold = title1Bold,
        title2Regular = title2Regular,
        title2Medium = title2Medium,
        title2Semibold = title2Semibold,
        title2Bold = title2Bold,
        title3Regular = title3Regular,
        title3Medium = title3Medium,
        title3Semibold = title3Semibold,
        title3Bold = title3Bold,
        heading1Regular = heading1Regular,
        heading1Medium = heading1Medium,
        heading1Semibold = heading1Semibold,
        heading1Bold = heading1Bold,
        heading2Regular = heading2Regular,
        heading2Medium = heading2Medium,
        heading2Semibold = heading2Semibold,
        heading2Bold = heading2Bold,
        headline1Regular = headline1Regular,
        headline1Medium = headline1Medium,
        headline1Semibold = headline1Semibold,
        headline1Bold = headline1Bold,
        headline2Regular = headline2Regular,
        headline2Medium = headline2Medium,
        headline2Semibold = headline2Semibold,
        headline2Bold = headline2Bold,
        body1NormalRegular = body1NormalRegular,
        body1NormalMedium = body1NormalMedium,
        body1NormalSemibold = body1NormalSemibold,
        body1NormalBold = body1NormalBold,
        body1ReadingRegular = body1ReadingRegular,
        body1ReadingMedium = body1ReadingMedium,
        body1ReadingSemibold = body1ReadingSemibold,
        body1ReadingBold = body1ReadingBold,
        body2NormalRegular = body2NormalRegular,
        body2NormalMedium = body2NormalMedium,
        body2NormalSemibold = body2NormalSemibold,
        body2NormalBold = body2NormalBold,
        body2ReadingRegular = body2ReadingRegular,
        body2ReadingMedium = body2ReadingMedium,
        body2ReadingSemibold = body2ReadingSemibold,
        body2ReadingBold = body2ReadingBold,
        label1NormalRegular = label1NormalRegular,
        label1NormalMedium = label1NormalMedium,
        label1NormalSemibold = label1NormalSemibold,
        label1NormalBold = label1NormalBold,
        label1ReadingRegular = label1ReadingRegular,
        label1ReadingMedium = label1ReadingMedium,
        label1ReadingSemibold = label1ReadingSemibold,
        label1ReadingBold = label1ReadingBold,
        label2Regular = label2Regular,
        label2Medium = label2Medium,
        label2Semibold = label2Semibold,
        label2Bold = label2Bold,
        caption1Regular = caption1Regular,
        caption1Medium = caption1Medium,
        caption1Semibold = caption1Semibold,
        caption1Bold = caption1Bold,
        caption2Regular = caption2Regular,
        caption2Medium = caption2Medium,
        caption2Semibold = caption2Semibold,
        caption2Bold = caption2Bold,
        caption3Regular = caption3Regular,
        caption3Medium = caption3Medium,
        caption3Semibold = caption3Semibold,
        caption3Bold = caption3Bold,
    )

    fun copy(
        display1Regular: TextStyle = this.display1Regular,
        display1Medium: TextStyle = this.display1Medium,
        display1Semibold: TextStyle = this.display1Semibold,
        display1Bold: TextStyle = this.display1Bold,
        display2Regular: TextStyle = this.display2Regular,
        display2Medium: TextStyle = this.display2Medium,
        display2Semibold: TextStyle = this.display2Semibold,
        display2Bold: TextStyle = this.display2Bold,
        title1Regular: TextStyle = this.title1Regular,
        title1Medium: TextStyle = this.title1Medium,
        title1Semibold: TextStyle = this.title1Semibold,
        title1Bold: TextStyle = this.title1Bold,
        title2Regular: TextStyle = this.title2Regular,
        title2Medium: TextStyle = this.title2Medium,
        title2Semibold: TextStyle = this.title2Semibold,
        title2Bold: TextStyle = this.title2Bold,
        title3Regular: TextStyle = this.title3Regular,
        title3Medium: TextStyle = this.title3Medium,
        title3Semibold: TextStyle = this.title3Semibold,
        title3Bold: TextStyle = this.title3Bold,
        heading1Regular: TextStyle = this.heading1Regular,
        heading1Medium: TextStyle = this.heading1Medium,
        heading1Semibold: TextStyle = this.heading1Semibold,
        heading1Bold: TextStyle = this.heading1Bold,
        heading2Regular: TextStyle = this.heading2Regular,
        heading2Medium: TextStyle = this.heading2Medium,
        heading2Semibold: TextStyle = this.heading2Semibold,
        heading2Bold: TextStyle = this.heading2Bold,
        headline1Regular: TextStyle = this.headline1Regular,
        headline1Medium: TextStyle = this.headline1Medium,
        headline1Semibold: TextStyle = this.headline1Semibold,
        headline1Bold: TextStyle = this.headline1Bold,
        headline2Regular: TextStyle = this.headline2Regular,
        headline2Medium: TextStyle = this.headline2Medium,
        headline2Semibold: TextStyle = this.headline2Semibold,
        headline2Bold: TextStyle = this.headline2Bold,
        body1NormalRegular: TextStyle = this.body1NormalRegular,
        body1NormalMedium: TextStyle = this.body1NormalMedium,
        body1NormalSemibold: TextStyle = this.body1NormalSemibold,
        body1NormalBold: TextStyle = this.body1NormalBold,
        body1ReadingRegular: TextStyle = this.body1ReadingRegular,
        body1ReadingMedium: TextStyle = this.body1ReadingMedium,
        body1ReadingSemibold: TextStyle = this.body1ReadingSemibold,
        body1ReadingBold: TextStyle = this.body1ReadingBold,
        body2NormalRegular: TextStyle = this.body2NormalRegular,
        body2NormalMedium: TextStyle = this.body2NormalMedium,
        body2NormalSemibold: TextStyle = this.body2NormalSemibold,
        body2NormalBold: TextStyle = this.body2NormalBold,
        body2ReadingRegular: TextStyle = this.body2ReadingRegular,
        body2ReadingMedium: TextStyle = this.body2ReadingMedium,
        body2ReadingSemibold: TextStyle = this.body2ReadingSemibold,
        body2ReadingBold: TextStyle = this.body2ReadingBold,
        label1NormalRegular: TextStyle = this.label1NormalRegular,
        label1NormalMedium: TextStyle = this.label1NormalMedium,
        label1NormalSemibold: TextStyle = this.label1NormalSemibold,
        label1NormalBold: TextStyle = this.label1NormalBold,
        label1ReadingRegular: TextStyle = this.label1ReadingRegular,
        label1ReadingMedium: TextStyle = this.label1ReadingMedium,
        label1ReadingSemibold: TextStyle = this.label1ReadingSemibold,
        label1ReadingBold: TextStyle = this.label1ReadingBold,
        label2Regular: TextStyle = this.label2Regular,
        label2Medium: TextStyle = this.label2Medium,
        label2Semibold: TextStyle = this.label2Semibold,
        label2Bold: TextStyle = this.label2Bold,
        caption1Regular: TextStyle = this.caption1Regular,
        caption1Medium: TextStyle = this.caption1Medium,
        caption1Semibold: TextStyle = this.caption1Semibold,
        caption1Bold: TextStyle = this.caption1Bold,
        caption2Regular: TextStyle = this.caption2Regular,
        caption2Medium: TextStyle = this.caption2Medium,
        caption2Semibold: TextStyle = this.caption2Semibold,
        caption2Bold: TextStyle = this.caption2Bold,
        caption3Regular: TextStyle = this.caption3Regular,
        caption3Medium: TextStyle = this.caption3Medium,
        caption3Semibold: TextStyle = this.caption3Semibold,
        caption3Bold: TextStyle = this.caption3Bold,
    ): LinkItTypography = LinkItTypography(
        display1Regular = display1Regular,
        display1Medium = display1Medium,
        display1Semibold = display1Semibold,
        display1Bold = display1Bold,
        display2Regular = display2Regular,
        display2Medium = display2Medium,
        display2Semibold = display2Semibold,
        display2Bold = display2Bold,
        title1Regular = title1Regular,
        title1Medium = title1Medium,
        title1Semibold = title1Semibold,
        title1Bold = title1Bold,
        title2Regular = title2Regular,
        title2Medium = title2Medium,
        title2Semibold = title2Semibold,
        title2Bold = title2Bold,
        title3Regular = title3Regular,
        title3Medium = title3Medium,
        title3Semibold = title3Semibold,
        title3Bold = title3Bold,
        heading1Regular = heading1Regular,
        heading1Medium = heading1Medium,
        heading1Semibold = heading1Semibold,
        heading1Bold = heading1Bold,
        heading2Regular = heading2Regular,
        heading2Medium = heading2Medium,
        heading2Semibold = heading2Semibold,
        heading2Bold = heading2Bold,
        headline1Regular = headline1Regular,
        headline1Medium = headline1Medium,
        headline1Semibold = headline1Semibold,
        headline1Bold = headline1Bold,
        headline2Regular = headline2Regular,
        headline2Medium = headline2Medium,
        headline2Semibold = headline2Semibold,
        headline2Bold = headline2Bold,
        body1NormalRegular = body1NormalRegular,
        body1NormalMedium = body1NormalMedium,
        body1NormalSemibold = body1NormalSemibold,
        body1NormalBold = body1NormalBold,
        body1ReadingRegular = body1ReadingRegular,
        body1ReadingMedium = body1ReadingMedium,
        body1ReadingSemibold = body1ReadingSemibold,
        body1ReadingBold = body1ReadingBold,
        body2NormalRegular = body2NormalRegular,
        body2NormalMedium = body2NormalMedium,
        body2NormalSemibold = body2NormalSemibold,
        body2NormalBold = body2NormalBold,
        body2ReadingRegular = body2ReadingRegular,
        body2ReadingMedium = body2ReadingMedium,
        body2ReadingSemibold = body2ReadingSemibold,
        body2ReadingBold = body2ReadingBold,
        label1NormalRegular = label1NormalRegular,
        label1NormalMedium = label1NormalMedium,
        label1NormalSemibold = label1NormalSemibold,
        label1NormalBold = label1NormalBold,
        label1ReadingRegular = label1ReadingRegular,
        label1ReadingMedium = label1ReadingMedium,
        label1ReadingSemibold = label1ReadingSemibold,
        label1ReadingBold = label1ReadingBold,
        label2Regular = label2Regular,
        label2Medium = label2Medium,
        label2Semibold = label2Semibold,
        label2Bold = label2Bold,
        caption1Regular = caption1Regular,
        caption1Medium = caption1Medium,
        caption1Semibold = caption1Semibold,
        caption1Bold = caption1Bold,
        caption2Regular = caption2Regular,
        caption2Medium = caption2Medium,
        caption2Semibold = caption2Semibold,
        caption2Bold = caption2Bold,
        caption3Regular = caption3Regular,
        caption3Medium = caption3Medium,
        caption3Semibold = caption3Semibold,
        caption3Bold = caption3Bold,
    )

    override fun equals(other: Any?): Boolean {
        if (this === other) return true
        if (other == null || this::class != other::class) return false

        other as LinkItTypography

        if (display1Regular != other.display1Regular) return false
        if (display1Medium != other.display1Medium) return false
        if (display1Semibold != other.display1Semibold) return false
        if (display1Bold != other.display1Bold) return false
        if (display2Regular != other.display2Regular) return false
        if (display2Medium != other.display2Medium) return false
        if (display2Semibold != other.display2Semibold) return false
        if (display2Bold != other.display2Bold) return false
        if (title1Regular != other.title1Regular) return false
        if (title1Medium != other.title1Medium) return false
        if (title1Semibold != other.title1Semibold) return false
        if (title1Bold != other.title1Bold) return false
        if (title2Regular != other.title2Regular) return false
        if (title2Medium != other.title2Medium) return false
        if (title2Semibold != other.title2Semibold) return false
        if (title2Bold != other.title2Bold) return false
        if (title3Regular != other.title3Regular) return false
        if (title3Medium != other.title3Medium) return false
        if (title3Semibold != other.title3Semibold) return false
        if (title3Bold != other.title3Bold) return false
        if (heading1Regular != other.heading1Regular) return false
        if (heading1Medium != other.heading1Medium) return false
        if (heading1Semibold != other.heading1Semibold) return false
        if (heading1Bold != other.heading1Bold) return false
        if (heading2Regular != other.heading2Regular) return false
        if (heading2Medium != other.heading2Medium) return false
        if (heading2Semibold != other.heading2Semibold) return false
        if (heading2Bold != other.heading2Bold) return false
        if (headline1Regular != other.headline1Regular) return false
        if (headline1Medium != other.headline1Medium) return false
        if (headline1Semibold != other.headline1Semibold) return false
        if (headline1Bold != other.headline1Bold) return false
        if (headline2Regular != other.headline2Regular) return false
        if (headline2Medium != other.headline2Medium) return false
        if (headline2Semibold != other.headline2Semibold) return false
        if (headline2Bold != other.headline2Bold) return false
        if (body1NormalRegular != other.body1NormalRegular) return false
        if (body1NormalMedium != other.body1NormalMedium) return false
        if (body1NormalSemibold != other.body1NormalSemibold) return false
        if (body1NormalBold != other.body1NormalBold) return false
        if (body1ReadingRegular != other.body1ReadingRegular) return false
        if (body1ReadingMedium != other.body1ReadingMedium) return false
        if (body1ReadingSemibold != other.body1ReadingSemibold) return false
        if (body1ReadingBold != other.body1ReadingBold) return false
        if (body2NormalRegular != other.body2NormalRegular) return false
        if (body2NormalMedium != other.body2NormalMedium) return false
        if (body2NormalSemibold != other.body2NormalSemibold) return false
        if (body2NormalBold != other.body2NormalBold) return false
        if (body2ReadingRegular != other.body2ReadingRegular) return false
        if (body2ReadingMedium != other.body2ReadingMedium) return false
        if (body2ReadingSemibold != other.body2ReadingSemibold) return false
        if (body2ReadingBold != other.body2ReadingBold) return false
        if (label1NormalRegular != other.label1NormalRegular) return false
        if (label1NormalMedium != other.label1NormalMedium) return false
        if (label1NormalSemibold != other.label1NormalSemibold) return false
        if (label1NormalBold != other.label1NormalBold) return false
        if (label1ReadingRegular != other.label1ReadingRegular) return false
        if (label1ReadingMedium != other.label1ReadingMedium) return false
        if (label1ReadingSemibold != other.label1ReadingSemibold) return false
        if (label1ReadingBold != other.label1ReadingBold) return false
        if (label2Regular != other.label2Regular) return false
        if (label2Medium != other.label2Medium) return false
        if (label2Semibold != other.label2Semibold) return false
        if (label2Bold != other.label2Bold) return false
        if (caption1Regular != other.caption1Regular) return false
        if (caption1Medium != other.caption1Medium) return false
        if (caption1Semibold != other.caption1Semibold) return false
        if (caption1Bold != other.caption1Bold) return false
        if (caption2Regular != other.caption2Regular) return false
        if (caption2Medium != other.caption2Medium) return false
        if (caption2Semibold != other.caption2Semibold) return false
        if (caption2Bold != other.caption2Bold) return false
        if (caption3Regular != other.caption3Regular) return false
        if (caption3Medium != other.caption3Medium) return false
        if (caption3Semibold != other.caption3Semibold) return false
        if (caption3Bold != other.caption3Bold) return false

        return true
    }

    override fun hashCode(): Int {
        return arrayOf(
            display1Regular,
            display1Medium,
            display1Semibold,
            display1Bold,
            display2Regular,
            display2Medium,
            display2Semibold,
            display2Bold,
            title1Regular,
            title1Medium,
            title1Semibold,
            title1Bold,
            title2Regular,
            title2Medium,
            title2Semibold,
            title2Bold,
            title3Regular,
            title3Medium,
            title3Semibold,
            title3Bold,
            heading1Regular,
            heading1Medium,
            heading1Semibold,
            heading1Bold,
            heading2Regular,
            heading2Medium,
            heading2Semibold,
            heading2Bold,
            headline1Regular,
            headline1Medium,
            headline1Semibold,
            headline1Bold,
            headline2Regular,
            headline2Medium,
            headline2Semibold,
            headline2Bold,
            body1NormalRegular,
            body1NormalMedium,
            body1NormalSemibold,
            body1NormalBold,
            body1ReadingRegular,
            body1ReadingMedium,
            body1ReadingSemibold,
            body1ReadingBold,
            body2NormalRegular,
            body2NormalMedium,
            body2NormalSemibold,
            body2NormalBold,
            body2ReadingRegular,
            body2ReadingMedium,
            body2ReadingSemibold,
            body2ReadingBold,
            label1NormalRegular,
            label1NormalMedium,
            label1NormalSemibold,
            label1NormalBold,
            label1ReadingRegular,
            label1ReadingMedium,
            label1ReadingSemibold,
            label1ReadingBold,
            label2Regular,
            label2Medium,
            label2Semibold,
            label2Bold,
            caption1Regular,
            caption1Medium,
            caption1Semibold,
            caption1Bold,
            caption2Regular,
            caption2Medium,
            caption2Semibold,
            caption2Bold,
            caption3Regular,
            caption3Medium,
            caption3Semibold,
            caption3Bold,
        ).contentHashCode()
    }
}
